[Doc Improvement][M365 developer mode][3546569]
MicrosoftDocs/m365copilot-docs pull request #5
Opened 2024-03-14 12:20 UTC by v-ypalikila

updated

2024-03-14 14:27 UTC, jasonjoh requested changes

2024-03-14 14:27 UTC, jasonjoh commented on docs/prerequisites.md
> +[!INCLUDE [preview-disclaimer](~/../msteams-docs/includes/bots/message-extension-plugin-developer-mode.md)]
This file does not exist in the msteams-docs repo main branch. In general I'm wary of re-using an include file from another repo this way - our builds will break if this include is moved or deleted.

2024-03-14 16:13 UTC, erikadoyle commented on docs/prerequisites.md
> -Developer mode is only available within **M365 Chat** (Copilot for Microsoft 365) experiences and doesn't surface in Microsoft Copilot (Copilot with Bing) chat. For more info, see [Debugging plugin s
I think this text should remain in the article, and a cross-repo include wouldn't be particularly helpful here. @v-ypalikila, I'll follow up with you and @jasonjoh on if/when to use cross-repo includes to de-dupe content within articles in Teams, Copilot, etc.

2024-05-08 12:58 UTC, jasonjoh commented
Closing due to inactivity.

2024-05-08 12:58 UTC, closed without merging